import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Learn (Foundations/Intermediate/Advanced) gets its own sidebar so
  // Advanced Concepts doesn't inherit these chapters (and vice versa).
  learnSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Foundations',
      link: {
        type: 'generated-index',
        description: 'Zero prior knowledge assumed. Start here. About 2 hours total across all 9 chapters.',
      },
      items: [{type: 'autogenerated', dirName: 'foundations'}],
    },
    {
      type: 'category',
      label: 'Intermediate',
      link: {
        type: 'generated-index',
        description: "For learners who've finished Foundations, or already have basic LLM/API experience.",
      },
      items: [{type: 'autogenerated', dirName: 'intermediate'}],
    },
    {
      type: 'category',
      label: 'Advanced',
      link: {
        type: 'generated-index',
        description: 'Production-adjacent GenAI engineering: multi-agent systems, advanced RAG, guardrails, observability.',
      },
      items: [{type: 'autogenerated', dirName: 'advanced'}],
    },
  ],

  advancedConceptsSidebar: [{type: 'autogenerated', dirName: 'advanced-concepts'}],
};

export default sidebars;
