import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Learn (Foundations/Intermediate/Advanced) gets its own sidebar so
  // Advanced Concepts doesn't inherit these chapters (and vice versa).
  learnSidebar: [
    'intro',
    {type: 'autogenerated', dirName: 'foundations'},
    {type: 'autogenerated', dirName: 'intermediate'},
    {type: 'autogenerated', dirName: 'advanced'},
  ],

  advancedConceptsSidebar: [{type: 'autogenerated', dirName: 'advanced-concepts'}],
};

export default sidebars;
