name = "fewshot-academy"
pages_build_output_dir = "build"
compatibility_date = "2026-08-04"

[[d1_databases]]
binding = "DB"
database_name = "fewshot-academy-analytics"
database_id = "16ff35b7-439c-48e5-b641-af82b20fe19d"
