name = "fewshot-email-worker"
main = "src/index.js"
compatibility_date = "2026-08-04"
compatibility_flags = ["nodejs_compat"]

[[queues.consumers]]
queue = "fewshot-anonymous-page-views"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 3
