import type {QuizQuestion} from '@site/src/components/Quiz';

export const questions: QuizQuestion[] = [
  {
    question:
      "How does a resource, like calculator://supported-operations in this lab's server, differ from a tool?",
    options: [
      'A resource requires arguments and a tool never does',
      "A resource is content a client reads directly, addressed by a URI, not something the agent's tool-calling loop decides to invoke mid-conversation the way it calls a tool",
      'Resources can only return numbers, tools can return any type',
      'There is no real difference, resource is just another name for tool',
    ],
    correctIndex: 1,
    explanation:
      "client.get_resources() fetches a resource's content directly, outside the agent's tool-calling loop. A tool, by contrast, is something the model decides to call based on the conversation.",
  },
  {
    question:
      "In docs_server.py, what does @mcp.prompt() actually produce when explain_answer(expression, answer) is called with arguments?",
    options: [
      'A response generated by a model running inside the server',
      'A filled-in text template, with no model involved on the server side; the client is the one that sends it to a model afterward',
      'A new MCP tool that gets registered automatically',
      'A cached answer from a previous run',
    ],
    correctIndex: 1,
    explanation:
      "The server just fills in a string template and hands it back. The server never calls a model itself, sampling is the only MCP primitive where a server can ask a model to generate something, and it works in the opposite direction (asking the client's model).",
  },
  {
    question:
      "What does client.get_prompt(...) return, and what does resources_and_prompts_agent.py do with it?",
    options: [
      "A raw string that's printed and discarded",
      'A list of chat messages, which the script passes straight into agent.ainvoke({"messages": prompt_messages}) the same shape create_agent expects for any conversation',
      'A new agent object ready to run',
      'A dictionary that must be converted to JSON before use',
    ],
    correctIndex: 1,
    explanation:
      "get_prompt() returns LangChain-compatible chat messages, which slot directly into the same {\"messages\": [...]} shape used everywhere else in this track, no conversion needed.",
  },
  {
    question:
      "The lab's README explains why sampling isn't demonstrated in this lab. Why not?",
    options: [
      'Sampling was removed from the MCP protocol',
      "The official MCP Python SDK supports sampling at the ClientSession level, but langchain-mcp-adapters (the wrapper every lab in this track uses) doesn't expose it as of this writing",
      'Sampling only works with OpenAI models, not Ollama or Anthropic',
      'Sampling requires a paid MCP server license',
    ],
    correctIndex: 1,
    explanation:
      "Sampling exists in the protocol and the raw SDK (ClientSession's sampling_callback), but this track's client wrapper doesn't currently support it, an honest gap rather than something MCP itself lacks.",
  },
];
